Ext.define('Assessmentapp.assessmentapp.web.com.view.assessmentcontext.survey.AssessmentQuestionSheetLoaderUI', {
     "xtype": "assessmentQuestionSheetLoaderUI",
     "name": "assessmentQuestionSheetLoader",
     "items": [{
          "xtype": "button",
          "name": "uploadData",
          "text": "Upload assessment questionarie",
          "margin": 5,
          "itemId": "podjooi",
          "listeners": {
               "click": "onuploadDataclick"
          }
     }, {
          "xtype": "grids",
          "name": "questionarieList",
          "title": "Questionaries ",
          "hiddenName": "Grid",
          "margin": 5,
          "collapseMode": "header",
          "border": true,
          "editTools": false,
          "features": [],
          "plugins": [{
               "ptype": "cellediting",
               "clicksToEdit": 1
          }],
          "columns": [{
               "xtype": "gridcolumn",
               "header": "questionId",
               "dataIndex": "questionId",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "question",
               "dataIndex": "question",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "questionDesc",
               "dataIndex": "questionDesc",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "questionInference",
               "dataIndex": "questionInference",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "createdBy",
               "hidden": true,
               "dataIndex": "createdBy",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "createdDate",
               "hidden": true,
               "dataIndex": "createdDate",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "updatedBy",
               "hidden": true,
               "dataIndex": "updatedBy",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "updatedDate",
               "hidden": true,
               "dataIndex": "updatedDate",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "versionId",
               "hidden": true,
               "dataIndex": "versionId",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "activeStatus",
               "hidden": true,
               "dataIndex": "activeStatus",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "txnAccessCode",
               "hidden": true,
               "dataIndex": "txnAccessCode",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "AssessmentAnswer",
               "hidden": true,
               "dataIndex": "assessmentAnswer",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "answerId",
               "hidden": true,
               "dataIndex": "answerId",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "answer",
               "hidden": true,
               "dataIndex": "answer",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "answerDesc",
               "hidden": true,
               "dataIndex": "answerDesc",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "createdBy",
               "hidden": true,
               "dataIndex": "createdBy",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "createdDate",
               "hidden": true,
               "dataIndex": "createdDate",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "updatedBy",
               "hidden": true,
               "dataIndex": "updatedBy",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "updatedDate",
               "hidden": true,
               "dataIndex": "updatedDate",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "versionId",
               "hidden": true,
               "dataIndex": "versionId",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "activeStatus",
               "hidden": true,
               "dataIndex": "activeStatus",
               "flex": 1
          }, {
               "xtype": "gridcolumn",
               "header": "txnAccessCode",
               "hidden": true,
               "dataIndex": "txnAccessCode",
               "flex": 1
          }],
          "itemId": "jijkabi",
          "store": {
               "model": "Assessmentapp.assessmentapp.shared.com.model.assessmentcontext.survey.AssessmentQuestionModel",
               "autoLoad": true,
               "autoSync": true,
               "proxy": {
                    "type": "ajax",
                    "url": "secure/AssessmentQuestion/findAll",
                    "actionMethods": {
                         "read": "GET"
                    },
                    "headers": {
                         "Content-Type": "application/json"
                    },
                    "extraParams": {},
                    "reader": {
                         "type": "json",
                         "rootProperty": "response.data"
                    }
               }
          },
          "tools": [{
               "type": "refresh",
               "tooltip": "Refresh Grid Data",
               "handler": "onGridRefreshClick"
          }]
     }],
     "border": true,
     "autoScroll": true,
     "title": "Assessment Questionarie Sheet Loader",
     "margin": 5,
     "itemId": "afhlbni",
     "dockedItems": [],
     "requires": ["Assessmentapp.assessmentapp.shared.com.model.assessmentcontext.survey.AssessmentQuestionModel", "Assessmentapp.assessmentapp.web.com.controller.assessmentcontext.survey.AssessmentQuestionSheetLoaderUIController", "Assessmentapp.assessmentapp.shared.com.viewmodel.assessmentcontext.survey.AssessmentQuestionSheetLoaderUIViewModel", "Assessmentapp.assessmentapp.shared.com.model.assessmentcontext.survey.AssessmentQuestionSheetLoaderUIModel", "Assessmentapp.view.fw.component.Grids"],
     "extend": "Ext.form.Panel",
     "viewModel": "AssessmentQuestionSheetLoaderUIViewModel",
     "controller": "AssessmentQuestionSheetLoaderUIController"
});